defmodule Id3vx.Frame.Labels do
  @moduledoc """
  Provides the full set of frames and their labels.

  Generated from priv/generate-labels.exs.
  """

  @labels %{
    "WPUB" => "Publishers official webpage",
    "OWNE" => "Ownership frame",
    "APIC" => "Attached picture",
    "WPAY" => "Payment",
    "TLAN" => "Language(s)",
    "TMCL" => "Musician credits list",
    "TSST" => "Set subtitle",
    "TDRC" => "Recording time",
    "SEEK" => "Seek frame",
    "TPE2" => "Band/orchestra/accompaniment",
    "POPM" => "Popularimeter",
    "ETCO" => "Event timing codes",
    "TCON" => "Content type",
    "TIT3" => "Subtitle/Description refinement",
    "TDLY" => "Playlist delay",
    "TOPE" => "Original artist(s)/performer(s)",
    "TOFN" => "Original filename",
    "UFID" => "Unique file identifier",
    "PRIV" => "Private frame",
    "TMED" => "Media type",
    "COMM" => "Comments",
    "POSS" => "Position synchronisation frame",
    "TRSN" => "Internet radio station name",
    "MLLT" => "MPEG location lookup table",
    "TSOA" => "Album sort order",
    "TSSE" => "Software/Hardware and settings used for encoding",
    "TKEY" => "Initial key",
    "WFED" => "Podcast link",
    "TRCK" => "Track number/Position in set",
    "TBPM" => "BPM (beats per minute)",
    "TALB" => "Album/Movie/Show title",
    "RVA2" => "Relative volume adjustment (2)",
    "TLEN" => "Length",
    "TPUB" => "Publisher",
    "PCNT" => "Play counter",
    "TDOR" => "Original release time",
    "TENC" => "Encoded by",
    "WXXX" => "User defined URL link frame",
    "TPRO" => "Produced notice",
    "AENC" => "Audio encryption",
    "LINK" => "Linked information",
    "TIT2" => "Title/songname/content description",
    "WOAF" => "Official audio file webpage",
    "TSOT" => "Title sort order",
    "WOAS" => "Official audio source webpage",
    "TPE4" => "Interpreted, remixed, or otherwise modified by",
    "TDTG" => "Tagging time",
    "TIPL" => "Involved people list",
    "RVRB" => "Reverb",
    "TCOP" => "Copyright message",
    "TEXT" => "Lyricist/Text writer",
    "TIT1" => "Content group description",
    "TOLY" => "Original lyricist(s)/text writer(s)",
    "TPE1" => "Lead performer(s)/Soloist(s)",
    "TOAL" => "Original album/movie/show title",
    "COMR" => "Commercial frame",
    "SYTC" => "Synchronised tempo codes",
    "WORS" => "Official Internet radio station homepage",
    "SIGN" => "Signature frame",
    "TMOO" => "Mood",
    "TSOP" => "Performer sort order",
    "SYLT" => "Synchronised lyric/text",
    "TDRL" => "Release time",
    "MCDI" => "Music CD identifier",
    "TDEN" => "Encoding time",
    "WCOP" => "Copyright/Legal information",
    "CHAP" => "Chapters",
    "USER" => "Terms of use",
    "WCOM" => "Commercial information",
    "EQU2" => "Equalisation (2)",
    "TCOM" => "Composer",
    "ASPI" => "Audio seek point index",
    "USLT" => "Unsynchronised lyric/text transcription",
    "TRSO" => "Internet radio station owner",
    "TPOS" => "Part of a set",
    "TXXX" => "User defined text information frame",
    "TOWN" => "File owner/licensee",
    "GRID" => "Group identification registration",
    "TSRC" => "ISRC (international standard recording code)",
    "TPE3" => "Conductor/performer refinement",
    "ENCR" => "Encryption method registration",
    "TFLT" => "File type",
    "RBUF" => "Recommended buffer size",
    "GEOB" => "General encapsulated object",
    "WOAR" => "Official artist/performer webpage"
  }

  def all do
    @labels
  end

  def from_id(id) do
    @labels[id]
  end
end
